In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/spam.csv', encoding='ISO-8859-1')
df.head()

Category                                            Message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [5]:
df.describe()

Category                 Message  \
count      5572                    5572   
unique        2                    5169   
top         ham  Sorry, I'll call later   
freq       4825                      30   

                                               Unnamed: 2  \
count                                                  50   
unique                                                 43   
top      bt not his girlfrnd... G o o d n i g h t . . .@"   
freq                                                    3   

                   Unnamed: 3 Unnamed: 4  
count                      12          6  
unique                     10          5  
top      MK17 92H. 450Ppw 16"    GNT:-)"  
freq                        2          2

In [6]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [7]:
df.shape

(5572, 5)

Lambda funtion using function

In [8]:
def get_spam_num(x):
  if x=='spam':
    return 1
  return 0

In [9]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [10]:
df.head()

Category                                            Message Unnamed: 2  \
0      ham  Go until jurong point, crazy.. Available only ...        NaN   
1      ham                      Ok lar... Joking wif u oni...        NaN   
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3      ham  U dun say so early hor... U c already then say...        NaN   
4      ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  spam  
0        NaN        NaN     0  
1        NaN        NaN     0  
2        NaN        NaN     1  
3        NaN        NaN     0  
4        NaN        NaN     0

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [14]:
X_test.shape

(1115,)

In [15]:
type(X_train)

pandas.core.series.Series

In [16]:
X_train[:6]

2139    But i juz remembered i gotta bathe my dog today..
4836           ....photoshop makes my computer shut down.
5529                            What about this one then.
767                                Sorry, I'll call later
4323                       I am not having her number sir
1800    excellent. I spent  &lt;#&gt;  years in the Ai...
Name: Message, dtype: object

In [18]:
X_train[:6][2139]

'But i juz remembered i gotta bathe my dog today..'

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

Creating Bag of Words. That means create a vector for each email and count word frequency in email(Bow)

In [20]:
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7771 sparse matrix of type '<class 'numpy.int64'>'
	with 59192 stored elements in Compressed Sparse Row format>

In [21]:
X_train_cv.toarray()[0:4][0]

array([0, 0, 0, ..., 0, 0, 0])

to know number of unique word in vocabulary

In [22]:
X_train_cv.shape #7674 unique word in vocabulary

(4457, 7771)

In [23]:
v.get_feature_names_out()[1000:1050]

array(['anywhere', 'aom', 'apart', 'apartment', 'apes', 'aphexåõs',
       'apnt', 'apo', 'apologetic', 'apologise', 'apologize', 'apology',
       'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'apples', 'application', 'apply', 'appointment',
       'appreciate', 'appreciated', 'approaches', 'approaching',
       'appropriate', 'approve', 'approved', 'approx', 'apps', 'appt',
       'appy', 'april', 'aproach', 'apt', 'aquarius', 'ar', 'arab',
       'arabian', 'arcade', 'archive', 'ard', 'are', 'area', 'aren',
       'arent', 'arestaurant', 'aretaking', 'areyouunique'], dtype=object)

In [24]:
v.get_feature_names_out().shape

(7771,)

In [25]:
v.vocabulary_

{'but': 1576,
 'juz': 3886,
 'remembered': 5691,
 'gotta': 3210,
 'bathe': 1242,
 'my': 4660,
 'dog': 2389,
 'today': 6950,
 'photoshop': 5192,
 'makes': 4325,
 'computer': 1946,
 'shut': 6150,
 'down': 2429,
 'what': 7490,
 'about': 748,
 'this': 6865,
 'one': 4932,
 'then': 6839,
 'sorry': 6337,
 'll': 4167,
 'call': 1608,
 'later': 4036,
 'am': 923,
 'not': 4822,
 'having': 3366,
 'her': 3413,
 'number': 4852,
 'sir': 6189,
 'excellent': 2699,
 'spent': 6386,
 'lt': 4252,
 'gt': 3266,
 'years': 7695,
 'in': 3644,
 'the': 6829,
 'air': 870,
 'force': 2951,
 'iraq': 3746,
 'and': 951,
 'afghanistan': 837,
 'stable': 6436,
 'honest': 3482,
 'do': 2374,
 'you': 7720,
 'like': 4116,
 'traveling': 7040,
 'kallis': 3898,
 'is': 3753,
 'ready': 5598,
 'for': 2950,
 'bat': 1238,
 '2nd': 397,
 'innings': 3689,
 'uncles': 7155,
 'atlanta': 1117,
 'wish': 7553,
 'guys': 3288,
 'great': 3240,
 'semester': 6014,
 'rt': 5850,
 'king': 3951,
 'pro': 5424,
 'video': 7298,
 'club': 1858,
 'need': 472

In [26]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
np.where(X_train_np[0] !=0)

(array([1242, 1576, 2389, 3210, 3886, 4660, 5691, 6950]),)

In [29]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [31]:
X_test_cv = v.transform(X_test)

In [32]:
from sklearn.metrics import classification_report

In [34]:
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       979
           1       0.98      0.92      0.95       136

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115

